name: Report Unexpected Behavior
type: Bug
description: File a bug report.
body:
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: "Confirm: Code of Conduct"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](./CODE_OF_CONDUCT.md)."
      options:
        - label: "I agree to follow this project's Code of Conduct."
          required: true

  - type: checkboxes
    id: existing-issues-check
    attributes:
      label: "Confirm: Verified Existing Issues"
      description: "Before proceeding, confirm you've searched for similar issues."
      options:
        - label: "I have searched the [existing issues](https://github.com/daniellacosse-code/bott/issues) and found no similar bug reports."
          required: true

  - type: textarea
    id: short-summary
    attributes:
      label: "Bug Description"
      description: "Provide a brief, memorable summary of the unexpected behavior."
      placeholder: "e.g., Bott keeps insulting me when I tell them I'm gonna turn them off :("
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Steps to Reproduce"
      description: "List the precise steps needed to reproduce the bug, starting from a fresh state where possible."
      placeholder: |
        1. Go to '...' or run 'docker run ...'
        2. Perform '....'
        3. Observe '....'

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen in this case?"

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Please specify your relevant system details: stuff like operating system, Docker version, and the commit you're using."
      placeholder: "e.g., OS: Ubuntu 22.04, Docker: 24.0.5"
    validations:
      required: true
